Repository Shuttlerock/actions, pull requests merged in 2020-11, with the labels that each got.

#152 [STUDIO-665] Avoid Docker Hub rate limits for your CircleCI builds
  .circleci/config.yml
  .meta/STUDIO-662.md
  .meta/STUDIO-665.md
Labels: passed-review

#151 [STUDIO-662] [Epic] Avoid Docker Hub rate limits for our CircleCI builds
  .meta/STUDIO-662.md
Labels: epic, in-progress

#169 [STUDIO-652] Allow a label to be added to Jira issues to skip PR creation
  .meta/STUDIO-652.md
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
  src/services/Github/__tests__/Epic.test.ts
  src/services/Github/__tests__/Label.test.ts
  src/services/Jira/Issue.ts
  src/services/Jira/__tests__/Issue.test.ts
  src/triggers/__tests__/createPullRequestForJiraIssue.test.ts
  src/triggers/createPullRequestForJiraIssue.ts
Labels: please-review

#176 [STUDIO-583] Add reviewers when a PR is set to `Ready for review`
  .github/workflows/pull-request-ready-for-review-action.yml
  .meta/STUDIO-583.md
  .secrets.example
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/action.yml
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  src/actions/pull-request-ready-for-review-action/__tests__/pullRequestReadyForReview.test.ts
  src/actions/pull-request-ready-for-review-action/action.yml
  src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
  src/services/Credentials.ts
  src/services/Github/PullRequest.ts
  src/services/Github/__tests__/PullRequest.test.ts
  src/services/Inputs.ts
  src/services/Jira/Issue.ts
  src/tests/Mocks.ts
  src/tests/Setup.ts
  src/tests/fixtures/github-pull-request-payload.json
Labels: big-pr, please-review
