Repository Shuttlerock/actions, pull requests merged in 2021-01, with the labels that each got.

#263 Release Candidate 2021-01-07-0455 (Quiet Quokka)
  package.json
  yarn.lock
Labels: in-progress, passed-review, release

#277 Release Candidate 2021-01-12-0426 (Explicit Eagle)
  .meta/STUDIO-1267.md
  .meta/STUDIO-1283.md
  actions/pull-request-ready-for-review-action/index.js
  src/actions/pull-request-ready-for-review-action/pullRequestReadyForReview.ts
Labels: please-review, release

#282 Release Candidate 2021-01-12-0722 (National Nightingale)
  .github/workflows/pull-request-closed-action.yml
  .meta/STUDIO-1249.md
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  package.json
  src/actions/pull-request-closed-action/__tests__/fixtures/release-merged.json
  src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
  src/actions/pull-request-closed-action/pullRequestClosed.ts
  src/services/Github/Release.ts
  src/services/Github/__tests__/Release.test.ts
  src/tests/Mocks.ts
  yarn.lock
Labels: please-review, release

#284 Release Candidate 2021-01-13-0405 (Free Flea)
  .github/workflows/pull-request-labeled-action.yml
  .meta/STUDIO-690.md
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
  src/actions/pull-request-labeled-action/pullRequestLabeled.ts
  src/services/Constants.ts
Labels: please-review, release

#288 Release Candidate 2021-01-13-0857 (Hidden Hoverfly)
  .meta/STUDIO-1291.md
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  package.json
  src/services/Github/Release.ts
  yarn.lock
Labels: please-review, release

#289 [STUDIO-1231] Create a Jira release when a release PR is merged
  .github/workflows/pull-request-closed-action.yml
  .meta/STUDIO-1231.md
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/action.yml
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/action.yml
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
  src/actions/pull-request-closed-action/action.yml
  src/actions/pull-request-closed-action/pullRequestClosed.ts
  src/services/Credentials.ts
  src/services/Github/PullRequest.ts
  src/services/Github/__tests__/PullRequest.test.ts
  src/services/Jira/Issue.ts
  src/services/Jira/Project.ts
  src/services/Jira/Release.ts
  src/services/Jira/__tests__/Issue.test.ts
  src/services/Jira/__tests__/Project.test.ts
  src/services/Jira/__tests__/Release.test.ts
  src/services/Jira/index.ts
  src/tests/Mocks.ts
Labels: please-review

#305 Release Candidate 2021-01-20-0802 (Leading Llama)
  .meta/STUDIO-1327.md
  actions/check-run-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  src/services/Jira/Release.ts
Labels: please-review, release

#306 [STUDIO-1344] Release demonstration bug
  .meta/STUDIO-1344.md
Labels: passed-review, please-review

#307 Release Candidate 2021-01-22-0109 (Beneficial Bovid)
  .meta/STUDIO-1344.md
Labels: passed-review, release

#313 Release Candidate 2021-01-22-1211 (Ordinary Owl)
  .meta/STUDIO-1346.md
  actions/check-run-completed-action/index.js
  actions/check-suite-completed-action/index.js
  src/actions/check-suite-completed-action/checkSuiteCompleted.ts
Labels: passed-review, please-review, release

#314 Release Candidate 2021-01-22-1247 (Juicy Jay)
  package.json
  yarn.lock
Labels: passed-review, release

#319 Release Candidate 2021-01-22-0136 (Kind Krill)
  .meta/STUDIO-1347.md
  .meta/STUDIO-1348.md
  actions/check-run-completed-action/index.js
  actions/check-suite-completed-action/index.js
  src/actions/check-suite-completed-action/checkSuiteCompleted.ts
Labels: please-review, release

#324 Release Candidate 2021-01-26-0540 (Russian Rooster)
  .meta/STUDIO-1359.md
  actions/check-run-completed-action/index.js
  actions/check-suite-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  package.json
  src/actions/check-suite-completed-action/checkSuiteCompleted.ts
  src/services/Github/Release.ts
  yarn.lock
Labels: passed-review, please-review, release
