Repository Shuttlerock/actions, pull requests merged in 2021-05, with the labels that each got.

#515 Release Candidate 2021-05-06-0257 (Qualified Quelea)
  .meta/SECURITY-381.md
  actions/check-run-completed-action/index.js
  actions/check-suite-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  package.json
  src/services/Template.ts
  yarn.lock
Labels: please-review, release

#534 Release Candidate 2021-05-20-0715 (Quickest Quail)
  .gitignore
  .meta/STUDIO-2037.md
  actions/check-run-completed-action/index.js
  actions/check-suite-completed-action/index.js
  actions/pull-request-closed-action/index.js
  actions/pull-request-converted-to-draft-action/index.js
  actions/pull-request-labeled-action/index.js
  actions/pull-request-ready-for-review-action/index.js
  actions/trigger-action/index.js
  package.json
  src/actions/check-run-completed-action/index.ts
  src/actions/check-suite-completed-action/__tests__/checkSuiteCompleted.test.ts
  src/actions/check-suite-completed-action/checkSuiteCompleted.ts
  src/actions/check-suite-completed-action/index.ts
  src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
  src/actions/pull-request-closed-action/index.ts
  src/actions/pull-request-closed-action/pullRequestClosed.ts
  src/actions/pull-request-converted-to-draft-action/__tests__/pullRequestConvertedToDraft.test.ts
  src/actions/pull-request-converted-to-draft-action/index.ts
  src/actions/pull-request-labeled-action/__tests__/pullRequestLabeled.test.ts
  src/actions/pull-request-labeled-action/index.ts
  src/actions/pull-request-ready-for-review-action/index.ts
  src/actions/rebase-epic-action/index.ts
  src/actions/trigger-action/index.ts
  src/services/Credentials.ts
  src/services/Github/Branch.ts
  src/services/Github/Epic.ts
  src/services/Github/Git.ts
  src/services/Github/Label.ts
  src/services/Github/PullRequest.ts
  src/services/Github/Release.ts
  src/services/Github/Repository.ts
  src/services/Github/__tests__/Branch.test.ts
  src/services/Github/__tests__/Git.test.ts
  src/services/Github/__tests__/PullRequest.test.ts
  src/services/Github/__tests__/Release.test.ts
  src/services/Jira/Issue.ts
  src/services/Jira/Project.ts
  src/services/Jira/Release.ts
  src/services/Slack/Message.ts
  src/services/String.ts
  src/services/Template.ts
  src/tests/Mocks.ts
  src/triggers/createPullRequestForJiraIssue.ts
  yarn.lock
Labels: passed-review, release

#537 Fix for Jira release boolean logic
  actions/pull-request-closed-action/index.js
  src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
  src/actions/pull-request-closed-action/pullRequestClosed.ts
  src/services/Credentials.ts
  src/tests/Mocks.ts
Labels: please-review

#538 Release Candidate 2021-05-21-1244 (Jolly Jaguar)
  actions/pull-request-closed-action/index.js
  package.json
  src/actions/pull-request-closed-action/__tests__/pullRequestClosed.test.ts
  src/actions/pull-request-closed-action/pullRequestClosed.ts
  src/services/Credentials.ts
  src/tests/Mocks.ts
  yarn.lock
Labels: passed-review, release

#542 [devops] Update repository configuration
  .github/PULL_REQUEST_TEMPLATE.md
Labels: please-review
